### PR TITLE
Make party page sync the party automatically

### PR DESCRIPTION
**Pull request by crookedneighbor**

### CODE REVIEW

**Comment by crookedneighbor** [comment]
Tag teaming this PR :smile:

**Comment by hairlessbear** [comment]
:+1: I really like this idea, but I'm not sure we should add it yet due to [#4816](https://github.com/HabitRPG/habitrpg/issues/4816). I think if we add this, it will mean that certain party members (in groups of 15 or larger) *never* show up, either in the members list, or in the invitation list.

**Comment by crookedneighbor** [comment]
Oh yeah. That wrinkle :cry:

**Comment by hairlessbear** [comment]
After some messing around with my local install, I think I've isolated the issue though. Maybe you'll have an idea how to fix it?

When the party page is loaded fresh (I tested by refreshing the page) `GET /api/v2/groups/party` is called, which means that [`populateQuery`](https://github.com/HabitRPG/habitrpg/blob/bd76b762e644300369e0a662fbe0a062217670df/website/src/controllers/groups.js#L38-51) works properly and doesn't limit the member list.

But when "Fetch Recent Messages" is pushed, `GET /api/v2/groups/6080b7ff-322e-437f-986a-1a17d8fca131` is called, resulting in `populateQuery` viewing the party as just another guild, and thus it limits the members and truncates the list.

The only problem is that I have no clue *why* this is happening. Do you have any idea?

**Comment by crookedneighbor** [comment]
Good detective work.

Probably because when the party page is getting loaded in, it passes the query `{'type': 'party'}`, which shows the behavior that you saw, while `group.$get()` calls `{'._id': 'party-id'}` in which case it gets treated like a guild. 

^ All speculation, have not looked at the code.

**Comment by hairlessbear** [comment]
Could you point me in the right direction for where in the code that information might be? I'm still extremely fuzzy on determining what calls result in what data getting sent where (<--terrifyingly worded sentence).

**Comment by crookedneighbor** [comment]
It's a little bit hacky, but this will get the job done for now.

**Comment by hairlessbear** [comment]
> It's a little bit hacky, but this will get the job done for now.

Famous last words :stuck_out_tongue_winking_eye:.

**Pull request merged**
