### PR TITLE
Quest invite modal on sync

### PR DESCRIPTION
**Pull request by crookedneighbor**
We're going to try to put as many watches on $scope instead of $rootScope. This one looked like it would be safe, but I'd be appreciative if you tested it out too before merging in the PR. 

Most of the commits are just from merging in develop. Here's the only relevant one for the PR: https://github.com/hairlessbear/habitrpg/commit/4fc04fea24889d3550cfb01f508466ff56c5ad40

### CODE REVIEW

**Comment by crookedneighbor** [comment]
I would just merge in this PR :smile:

**Comment by hairlessbear** [comment]
Oh yea, I forgot that I can always revert or change things if they don't work. Duh.

I'm totally going to blame you for putting the idea in my head that I should test before merging, since you suggested it in the first message of this PR. I refuse to accept responsibility :stuck_out_tongue_winking_eye: 

Actually...if this gets merged in as-is, it'll make the "changed files" section a mess, since it'll add all of the recent changes to `develop`. If I understand correctly, the best way to avoid that is to rebase, and then cherry-pick your relevant commits, right?

**Comment by crookedneighbor** [comment]
Noooooooooo... more thorough explanation in a minute. Don't try rebasing.

**Comment by hairlessbear** [comment]
Haha that's why I asked. My git-fu is much better than it was a couple months ago, but still pretty weak, especially when it comes to more complex situations such as this.

**Comment by crookedneighbor** [comment]
On my branch, which I branched off of your branch that is being PRed in habitrpg/habitrpg#5298, I merged in the most recent changes from the develop branch. That means I got the exact commits and my previous commits, and yours, stayed the same. 

If I had done a rebase off of develop, that would have meant that the commits I got from develop were the same commits, but the commits that you made on your branch and the commits I made on my branch would be recreated. The changes would be the same, but they would have new shas. (the long string of letters and numbers that identifies a commit) That would have resulted in you seeing your commits from your original branch, but with different shas, in the list of commits for this pr. 

Rebasing is most ideal when you haven't pushed your changes to a remote branch (like Github) yet. If you rebase after you push, you'll get a notice that there are changes on your local branch that are not on your remote one and changes on your remote branch that are not on your local one. You can overcome this by doing a `git push --force` to override the remote branch with the new version of the commits, but only do that if you're the only one working on that branch. 

If multiple people are touching the branch, I'll just do a regular merge. It means you get an extra bit of noise from the commit that is just saying you merged in the changes from develop, but that's much more preferable to me than getting locked into a rebasing nightmare. 

___

Now, as for how to test this change before merging in (I misread what you were asking me earlier), there's a hard way and an easy way. 

The hard way is to click on the link in the merge box that says: "You can also merge branches on the  command line." That'll give you instructions for how to check out the branch locally.

The easy way would be to install [hub](https://github.com/github/hub), which is a tool made by github to make doing things like this easier. It requires homebrew, but once homebrew is installed, all you need to do to install hub is go on your terminal and type `brew install hub`. 

From there, you can checkout a PR by typing `hub checkout https://github.com/path/to/pr`, so for this one you'd type: `hub checkout https://github.com/hairlessbear/habitrpg/pull/9` and it'll do all the magic of setting up the remotes and pulling down the branch in the "hard way" instructions. 

When you're done testing and you want to merge, you can do that one of two ways:

1) Press the merge button on this PR and then pull on your local branch
2) Checkout your local branch, merge in the new branch that hub created for you and push to the remote one (will also automatically merge the PR)

___

Does all that make sense?

**Comment by hairlessbear** [comment]
That does make sense (thanks for the thorough explanation, btw). I really, *really* don't like all the added noise though. I find it extremely useful to compare the work on a given branch to develop, and adding in all that noise makes it much more difficult. It's not the end of the world of course, just obnoxious. 

In terms of testing, I'm going to use "the hard method". It'll help me get better with git :smile:

Unfortunately, I'm about to go help a friend move, so I won't be able to test this until later today. Should still be done today though.

**Comment by hairlessbear** [comment]
When I tried to run `npm start`, this happened:

> [nodemon] v1.2.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node ./website/src/server.js`

>events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1043:14)
    at listen (net.js:1065:10)
    at Server.listen (net.js:1139:5)
    at Object.<anonymous> (/home/david/git/habitrpg/website/src/server.js:139:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
[nodemon] app crashed - waiting for file changes before starting...

I can't debug it right now, but I thought you'd like to know.

**Comment by crookedneighbor** [comment]
Looks like you already have something running on port 3000. Probably another instance of habitrpg, would be my guess.

If not, restart your computer and try again.

**Comment by hairlessbear** [comment]
Gah, I forgot I was running a separate instance of `npm` on my other workspace, for a different project. That's embarrassing. Glad to know there's not a problem though. I'll test this once I get back from moving. Thanks!

**Comment by crookedneighbor** [comment]
Same thing has happened to me many a time. I wish we didn't use the default port (3000) in the example config.json. Very easy to collide with other ports.

**Comment by hairlessbear** [comment]
Sorry for the delay. I'm testing this now. Assuming everything works as expected, I should have this merged soon.

On the default port issue, is there any particular reason we can't change it?

**Comment by hairlessbear** [comment]
No surprise, everything worked as expected.

**Comment by crookedneighbor** [comment]
Re: default port issue - mostly inertia. But also, port 3000 is the default for node apps, and if you're using it for something else, you can always change the value in your config.json. So on some level, it just doesn't make sense to change it

Thanks for spotting my faulty logic in the watch. Very excited to have this merged in soon.

**Pull request merged**
